default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: kauntaa_development
test: &test
  <<: *default
  database: kauntaa_test
production:
  <<: *default
  database: kauntaa_production
  username: kauntaa
  password: <%= ENV['KAUNTAA_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test