default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: kauntaa_development
test: &test
  <<: *default
  database: kauntaa_test
staging:
  <<: *default
  database: kauntaa_staging
  username: kauntaa_staging
  password: <%= ENV['KAUNTAA_DATABASE_PASSWORD'] %>
production:
  <<: *default
  database: kauntaa
  username: kauntaa
  password: <%= ENV['KAUNTAA_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
