default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: kauntaa_development
test: &test
  <<: *default
  database: kauntaa_test
cucumber:
  <<: *test
