d3.select("[data-counter-id='<%= @counter.id %>'] .counter-value")
.text("<%= @counter.clean_value %>")
.transition()
  .duration(200)
  .style('font-size', '50px')
  .attr('transform', "rotate(0 90 0)")
.transition()
  .duration(200)
  .style('font-size', '14px')
  .attr('transform', "rotate(0 0 0)")
