d3.select("[data-counter-id='<%= @counter.id %>'] .counter-value")
# .style('font-size', '2.5em')
.transition()
  .text("<%= @counter.clean_value %>")
  .duration(1000)
  .style('font-size', '4px')
  # .attr('transform', "rotate(0, 90, 0)")
.transition()
  .duration(400)
  .style('font-size', '14px')
  # .attr('transform', "rotate(0, 0, 0)")
